import Navbar from "@/components/Layout/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Layout/Footer/Footer";
import ReduxProvider from "@/redux/provider";

export const metadata: Metadata = {
    title: "Kawshik Biswas",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html>
            <body className="container">
                <ReduxProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
